{{- if .Values.customResourceDefinitions.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: parquet-streams.streaming.sneaksanddata.com
spec:
  group: streaming.sneaksanddata.com
  scope: Namespaced
  names:
    plural: parquet-streams
    singular: parquet-stream
    kind: ParquetStream
    shortNames:
      - pstream
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Source location
          type: string
          jsonPath: .spec.sourceSettings.baseLocation
        - name: Change Capture Interval
          type: string
          jsonPath: .spec.sourceSettings.changeCaptureIntervalSeconds
        - name: Sink location
          type: string
          jsonPath: .spec.sinkSettings.targetTableName
        - name: Phase
          type: string
          jsonPath: .status.phase
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tableProperties:
                  type: object
                  default:
                    partitionExpressions: []
                    sortedBy: []
                    parquetBloomFilterColumns: []
                    format: PARQUET
                  properties:
                    partitionExpressions:
                      type: array
                      items:
                        type: string
                      default: []
                    sortedBy:
                      type: array
                      items:
                        type: string
                      default: [ ]
                    parquetBloomFilterColumns:
                      type: array
                      items:
                        type: string
                      default: [ ]
                    format:
                      type: string
                      enum:
                        - PARQUET
                        - ORC
                        - AVRO
                      default: PARQUET
                sourceSettings:
                  type: object
                  properties:
                    changeCaptureIntervalSeconds:
                      type: integer
                      description: How long to wait before polling for next change set. Accepted range is between 1s and 3600s
                      minimum: 1
                      maximum: 3600
                    baseLocation:
                      type: string
                      description: Location root for Parquet files in a form of HDFS address s3a://, abfss:// etc.
                    tempPath:
                      type: string
                      description: Location to store temporary files
                      default: /tmp/parquet-stream
                    primaryKeys:
                      type: array
                      items:
                        type: string
                    useNameMapping:
                      type: boolean
                      description: |
                        Enable column projection using field names instead of field ids: https://iceberg.apache.org/spec/?column-projection#column-projection. 
                        This is identical to using `schema.name-mapping.default` with other Iceberg clients. Arcane with automatically generate field mapping from the source Parquet file. 
                        Note that this might negatively interact with existing column mapping on the file, if present. 
                        In most cases you do not need to enable this, unless a source Parquet file is written by code that doesn't assign field identifiers.
                      default: false
                    sourceSchema:
                      type: string
                      description: Optional base64-encoded empty Parquet file bytes. Will be used as a schema for the source. If not provided, schema will be inferred from a random file in the source path - which may fail if the path is empty.
                      default: ""
                    metastore:
                      type: object
                      default: null
                      properties:
                        schemaName:
                          type: string
                          description: Schema where the metastore table is located
                        tableName:
                          type: string
                          description: Name of the metastore table
                    s3:
                      type: object
                      properties:
                        usePathStyle:
                          type: boolean
                          default: false
                        region:
                          type: string
                          default: us-east-1
                        endpoint:
                          type: string
                          default: s3.amazonaws.com
                        maxResultsPerPage:
                          type: integer
                          default: 1000
                          minimum: 1
                          maximum: 1000
                        retryMaxAttempts:
                          type: integer
                          default: 5
                          minimum: 1
                          maximum: 10
                        retryBaseDelay:
                          type: number
                          default: 0.1
                          minimum: 0.1
                          maximum: 1
                        retryMaxDelay:
                          type: number
                          default: 1
                          minimum: 0.2
                          maximum: 2
                streamConfigurationSecretRef:
                  description: |
                    Name of the secret containing the stream configuration credentials. Must contain a ARCANE_FRAMEWORK__MERGE_SERVICE_CONNECTION_URI key
                  type: object
                  properties:
                    name:
                      type: string
                jobTemplateRef:
                  description: |
                    Name of the job template to be used for the streaming job if stream is running in normal mode.
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                backfillJobTemplateRef:
                  description: |
                    Name of the job template to be used for the streaming job if stream is running in the backfill mode.
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                rowsPerGroup:
                  type: integer
                  description: Maximum number of rows to be grouped together for the staging process to consume.
                groupingIntervalSeconds:
                  type: integer
                  description: Max time to wait for rowsPerGroup to accumulate and then proceed to staging. Can be from 1 to 60 seconds.
                  minimum: 1
                  maximum: 60
                sinkSettings:
                  type: object
                  properties:
                    optimizeSettings:
                      type: object
                      description: Configuration for target table optimize (data file aggregation into bigger files)
                      properties:
                        batchThreshold:
                          type: integer
                          default: 60
                          description: Number of batches to accumulate before triggering the OPTIMIZE
                        fileSizeThreshold:
                          type: string
                          default: 100MB
                          description: File size to target when running OPTIMIZE
                      default:
                        batchThreshold: 60
                        fileSizeThreshold: 100MB
                    snapshotExpirationSettings:
                      type: object
                      description: Configuration for EXPIRE SNAPSHOTS (table transaction log cutoff)
                      properties:
                        batchThreshold:
                          type: integer
                          default: 60
                          description: Number of batches to accumulate triggering EXPIRE SNAPSHOTS
                        retentionThreshold:
                          type: string
                          default: 6h
                          description: Maximum age of records in the transaction log to keep
                      default:
                        batchThreshold: 60
                        retentionThreshold: 6h
                    orphanFilesExpirationSettings:
                      type: object
                      description: Configuration for EXPIRE ORPHAN FILES (cleanup of files no longer referenced by Iceberg snapshots)
                      properties:
                        batchThreshold:
                          type: integer
                          default: 60
                          description: Number of batches to accumulate before triggering EXPIRE ORPHAN FILES
                        retentionThreshold:
                          type: string
                          default: 6h
                          description: Maximum age of files to keep while running this procedure
                      default:
                        batchThreshold: 60
                        retentionThreshold: 6h
                    analyzeSettings:
                      type: object
                      description: Configuration for ANALYZE (full refresh of extended statistics on the target)
                      properties:
                        batchThreshold:
                          type: integer
                          default: 60
                          description: Number of batches to accumulate before running the ANALYZE query.
                        includedColumns:
                          type: array
                          description: Columns to include in the ANALYZE query. If empty, ALL columns will be included.
                          items:
                            type: string
                          default: []
                      default:
                        batchThreshold: 60
                        includedColumns: []
                    targetTableName:
                      type: string
                      description: Name of the target table in the Iceberg catalog. Must be fully qualified as catalog.schema.table
                    sinkCatalogSettings:
                      type: object
                      description: Connection settings for Iceberg REST Catalog for the sink (target). This is used by watermarking process.
                      properties:
                        namespace:
                          type: string
                        warehouse:
                          type: string
                        catalogUri:
                          type: string
                lookBackInterval:
                  type: integer
                  description: |
                    DEPRECATED - TO BE REMOVED IN 2.1 RELEASE. DO NOT USE THIS SETTING!
                    
                    Number of seconds to look back when determining first set of changes to extract.
                    Can be set in interval from 1 second to 10 hours. Default is 1 hour.
                  minimum: 1
                  maximum: 1209600
                  default: 3600
                stagingDataSettings:
                  type: object
                  properties:
                    dataLocation:
                      type: string
                      description: Option data location override. Only use this setting for debugging and never in production environments.
                    maxRowsPerFile:
                      type: integer
                      description: The maximum number of rows per each data file in the staging table.
                      default: 10000
                    tableNamePrefix:
                      type: string
                      description: Prefix for staging tables created by Arcane. Must be UNIQUE in the WAREHOUSE scope.
                    catalog:
                      type: object
                      description: Settings for Iceberg REST Catalog used for staging tables
                      properties:
                        catalogName:
                          type: string
                        schemaName:
                          type: string
                        warehouse:
                          type: string
                        catalogUri:
                          type: string
                backfillBehavior:
                  type: string
                  enum:
                    - merge
                    - overwrite
                  default:
                    overwrite
                fieldSelectionRule:
                  type: object
                  description: INCLUDE will only use fields provided. You must specify mandatory fields like ARCANE_MERGE_KEY as well. EXCLUDE will exclude provided fields instead. ALL (default) will use all fields without filters.
                  properties:
                    ruleType:
                      type: string
                      enum:
                        - include
                        - exclude
                        - all
                    fields:
                      type: array
                      items:
                        type: string
                  default:
                    ruleType: all
                    fields: []
                backfillStartDate:
                  description: |
                    The date and time to start backfilling data from.
                    The date should be a valid Epoch timestamp in seconds
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - RESTARTING
                    - RUNNING
                    - RELOADING
                    - TERMINATING
                    - STOPPED
                    - SUSPENDED
                    - FAILED
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      message:
                        type: string
                      type:
                        type: string
                        enum:
                          - WARNING
                          - ERROR
                          - INFO
                          - READY
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
  {{- end }}
